# Generated by Django 3.0.2 on 2020-02-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200209_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('practice', models.CharField(choices=[('T', 'Toy Problem'), ('P', 'Project'), ('A', 'Application')], default='T', max_length=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Language')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
